version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_WS_URL=${VITE_WS_URL:-ws://localhost:5123/api/ws/}
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5123/api/}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 