MAP_HEIGHT = 1000
MAP_WEIGHT = 1000
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASSWORD = None
UPDATE_CHANNEL = "update_channel"
BROADCAST_CHANNEL = "broadcast_channel"

API_HOST = "0.0.0.0"
API_PORT = 5000
